name: mgame
description: "The M Game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  sqflite: ^2.3.0
  uuid: ^4.0.0
  path: ^1.8.3

  flutter_native_splash: ^2.3.8
  shared_preferences: ^2.2.2
  go_router: ^13.0.0

  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  logging: ^1.2.0

  flutter_animate: ^4.4.0
  
  flame: ^1.15.0
  flame_bloc: ^1.10.9
  
  wakelock_plus: ^1.1.3

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  flame_riverpod: ^5.2.0
  flame_audio: ^2.10.0

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9

  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

  build_runner: ^2.4.7

  riverpod_generator: ^2.3.9

  freezed: ^2.4.5
  json_serializable: ^6.7.1

  flutter_launcher_icons: ^0.13.1

  flutter_gen_runner:



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/garbage/
    - assets/images/trucks/
    - assets/images/trucks/stacked/
    - assets/images/tiles/
    - assets/images/tiles/forest/
    - assets/images/tiles/arrows/
    - assets/images/ui/
    - assets/images/ui/dialog/
    - assets/images/buildings/
    - assets/images/buildings/city/
    - assets/images/buildings/garbage_conveyor/
    - assets/images/buildings/garbage_loader/
    - assets/images/buildings/recycler/
    - assets/images/buildings/incinerator/
    - assets/images/buildings/garage/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC-Bold.ttf

    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
          weight: 400
        - asset: assets/fonts/Play-Bold.ttf
          weight: 700 


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#182F46"
    theme_color: "#182F46"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"


flutter_native_splash:
  color: "#182F46"
  image: assets/icons/icon.png

  android_12:
    color: "#182F46"
    icon_background_color: "#182F46"
    color_dark: "#182F46"
    icon_background_color_dark: "#182F46"