import 'package:flame/components.dart';
import 'package:flame_riverpod/flame_riverpod.dart';
import 'package:mgame/flame_game/buildings/incinerator/incinerator.dart';
import 'package:mgame/flame_game/menu/addon_toggle_accept_waste.dart';

import '../level.dart';
import '../riverpod_controllers/game_user_controller.dart';
import '../utils/my_text_style.dart';

import 'dialog_button.dart';
import 'menu_without_tabs.dart';

class MenuIncinerator extends MenuWithoutTabs with RiverpodComponentMixin {
  MenuIncinerator() : super(boxSize: Vector2(700, 450));

  late final DialogButton upgradePollutionReduction;
  late final DialogButton upgradeMoneyBonus;
  late final DialogButton upgradeFilter;

  bool isFetchingData = false;

  @override
  void onLoad() {
    super.onLoad();

    Incinerator thisIncinerator = game.currentlySelectedBuilding as Incinerator;

    world.add(AddonToggleAcceptWaste(position: Vector2(0, boxSize.y / 2)));

    ///
    ///
    /// TITLE
    world.add(TextComponent(
      text: "INCINERATOR",
      textRenderer: MyTextStyle.title,
      anchor: Anchor.topCenter,
      position: Vector2(0, -boxSize.y / 2 + 20),
    ));

    ///
    ///
    /// TEXT
    world.add(TextComponent(
      text: 'This factory burns garbage. It generates pollution.\nGarbage processed this way earn you money.',
      textRenderer: MyTextStyle.text,
      anchor: Anchor.topCenter,
      position: Vector2(0, -boxSize.y / 2 + 80),
    ));

    ///
    ///
    /// UPGRADES

    world.add(TextComponent(
      text: 'Install pollution filter   5K\$\nReduce pollution generated by 25%',
      textRenderer: MyTextStyle.text,
      anchor: Anchor.centerLeft,
      position: Vector2(-boxSize.x / 2 + 20, -boxSize.y / 2 + 180),
    ));
    if (thisIncinerator.pollutionReductionUpgrade) {
      world.add(TextComponent(
        text: 'Upgrade Bought',
        textRenderer: MyTextStyle.text,
        anchor: Anchor.center,
        position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 180),
      ));
    } else {
      world.add(upgradePollutionReduction = DialogButton(
        text: 'Buy upgrade',
        onPressed: () {
          if ((game.findByKeyName('level') as Level).money.hasEnoughMoney(5000)) {
            (game.findByKeyName('level') as Level).money.addValue(-5000);
            thisIncinerator.upgradePollutionReduction();
            if (upgradePollutionReduction.isMounted) {
              world.remove(upgradePollutionReduction);
              world.add(TextComponent(
                text: 'Upgrade Bought',
                textRenderer: MyTextStyle.text,
                anchor: Anchor.center,
                position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 180),
              ));
            }
          }
        },
        buttonSize: Vector2(200, 50),
        position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 180),
      ));
    }

    ///

    world.add(TextComponent(
      text: 'Generate BioMass   8K\$\nIncrease money earned by 25%',
      textRenderer: MyTextStyle.text,
      anchor: Anchor.centerLeft,
      position: Vector2(-boxSize.x / 2 + 20, -boxSize.y / 2 + 280),
    ));

    if (thisIncinerator.moneyBonusUpgrade) {
      world.add(TextComponent(
        text: 'Upgrade Bought',
        textRenderer: MyTextStyle.text,
        anchor: Anchor.center,
        position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 280),
      ));
    } else {
      world.add(upgradeMoneyBonus = DialogButton(
        text: 'Buy upgrade',
        onPressed: () {
          if ((game.findByKeyName('level') as Level).money.hasEnoughMoney(8000)) {
            (game.findByKeyName('level') as Level).money.addValue(-8000);
            thisIncinerator.upgradeMoneyBonus(1.25);

            if (upgradeMoneyBonus.isMounted) {
              world.remove(upgradeMoneyBonus);
              world.add(TextComponent(
                text: 'Upgrade Bought',
                textRenderer: MyTextStyle.text,
                anchor: Anchor.center,
                position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 280),
              ));
            }
          }
        },
        buttonSize: Vector2(200, 50),
        position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 280),
      ));
    }

    ///

    world.add(TextComponent(
      text: "Improve filters   3 EcoCredits\nReduce pollution generated by 50%",
      textRenderer: MyTextStyle.text,
      anchor: Anchor.centerLeft,
      position: Vector2(-boxSize.x / 2 + 20, -boxSize.y / 2 + 380),
    ));

    if (thisIncinerator.filterUpgrade) {
      world.add(TextComponent(
        text: 'Upgrade Bought',
        textRenderer: MyTextStyle.text,
        anchor: Anchor.center,
        position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 380),
      ));
    } else {
      world.add(upgradeFilter = DialogButton(
        text: 'Buy upgrade',
        onPressed: () async {
          if (!isFetchingData) {
            isFetchingData = true;
            upgradeFilter.textComponent.text = "Loading";
            String upgradeText = "";

            int ecoCredits = ref.read(gameUserControllerProvider.notifier).getUserEcoCredits();
            if (ecoCredits >= 3) {
              upgradeText = 'Upgrade Bought';
              ref.read(gameUserControllerProvider.notifier).updateGameUser(ecoCredits: ecoCredits - 3);
              thisIncinerator.upgradeFilter();
            } else {
              upgradeText = 'Insufficient EcoCredits';
            }
            if (upgradeFilter.isMounted) {
              upgradeFilter.removeFromParent();
            }
            world.add(TextComponent(
              text: upgradeText,
              textRenderer: MyTextStyle.text,
              anchor: Anchor.center,
              position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 380),
            ));
            isFetchingData = false;
          }
        },
        buttonSize: Vector2(200, 50),
        position: Vector2(boxSize.x / 2 - 150, -boxSize.y / 2 + 380),
      ));
    }
  }
}
