import 'package:flame/components.dart';

class DialogBDD {
  static const List<String> tutorial = [
    "Hello, it's about time you arrived! Everyone is in place to launch this innovative project.",
    "Citizens all around the world are randomly selected to find the best way to deal with waste. And you're next!",
    "I'm in charge of the newcomer training program. Let me show you around.",
    "This is the garage. This is where you can buy the vehicles you need to transport waste.",
    "But beware, some of them pollute enormously. Waste treatment is your main objective, but not at the expense of the environment.",
    "By the way, keep a close eye on this pollution gauge. If it fills up, you lose!",
    "On the other hand, this gauge indicates your progress in waste processing. If you manage to fill it, you win the game! In fact... you just move on to the next level. It's not going to be that easy...",
    "Oh, and one small detail. Most of what you do will cost you money. So make sure you don't run out of funds.",
    "How do you make money? Well, by processing waste, of course! These residents would be delighted if you could help them with their rubbish. And they'll pay you to take care of it.",
    "You'll need to build a waste loader at the indicated location to enable your vehicles to collect the waste.",
    "Then don't forget to build a road from the garage to the waste loader.",
    "Everything ok? ... Oh, I forgot one thing. When your vehicle is full of waste, think about building a waste treatment station.",
    "There are a number of ways to treat waste. Incinerate it, recycle it, ... but I'll leave you to experiment!",
    "Just bear in mind that not all processes are equally polluting. But some are slower, or cost more, or don't apply to all types of waste. Now you know why we need your help!",
    "Let's start with an incinerator, simple, efficient but... polluting. You'll have to improve this solution as soon as possible.",
    "It's time for action! Click on the garage to buy a vehicle and help the residents before they're overrun by garbage. This would generate... pollution! Good luck!",
    "If you need me to explain it all again, just come and see me in the main menu. See you soon!",
  ];

  static List<Vector2> tutorialAvatarPositions = [
    Vector2(625, 250),
    Vector2(625, 250),
    Vector2(625, 250),
    Vector2(50, 220),
    Vector2(50, 220),
    Vector2(900, 100),
    Vector2(900, 100),
    Vector2(900, 100),
    Vector2(800, 500),
    Vector2(800, 500),
    Vector2(200, 500),
    Vector2(625, 250),
    Vector2(625, 250),
    Vector2(625, 250),
    Vector2(900, 500),
    Vector2(625, 250),
    Vector2(625, 250),
  ];
  static List<Vector2> tutorialHighlightPositions = [
    Vector2(0, 0),
    Vector2(0, 0),
    Vector2(0, 0),
    Vector2(250, 110),
    Vector2(0, 0),
    Vector2(1400, -200),
    Vector2(600, -200),
    Vector2(1000, -80),
    Vector2(1800, 675),
    Vector2(1700, 710),
    Vector2(1000, 500),
    Vector2(0, 0),
    Vector2(0, 0),
    Vector2(0, 0),
    Vector2(1250, 400),
    Vector2(0, 0),
    Vector2(0, 0),
  ];

  static List<double> tutorialHighlightRadius = [
    0,
    0,
    0,
    175,
    0,
    400,
    400,
    150,
    175,
    100,
    800,
    0,
    0,
    0,
    200,
    0,
    0,
  ];
}
