// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8y7z8u_JgBrahqAB_HT-ggPYvikQhFI',
    appId: '1:439365888460:web:3b670faee62519a1a79569',
    messagingSenderId: '439365888460',
    projectId: 'mgame-8c88b',
    authDomain: 'mgame-8c88b.firebaseapp.com',
    storageBucket: 'mgame-8c88b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMu44u-F_HrbBcet6yemhNYHFBMTPCz_c',
    appId: '1:439365888460:android:aed0e3ca45d3286ea79569',
    messagingSenderId: '439365888460',
    projectId: 'mgame-8c88b',
    storageBucket: 'mgame-8c88b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnljV0rd5eOQJDxIAAOT2DelKOvDkl37U',
    appId: '1:439365888460:ios:9ec8f822483bfacca79569',
    messagingSenderId: '439365888460',
    projectId: 'mgame-8c88b',
    storageBucket: 'mgame-8c88b.appspot.com',
    iosBundleId: 'com.beyondthebox.mgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnljV0rd5eOQJDxIAAOT2DelKOvDkl37U',
    appId: '1:439365888460:ios:49a88b168c1e8f7aa79569',
    messagingSenderId: '439365888460',
    projectId: 'mgame-8c88b',
    storageBucket: 'mgame-8c88b.appspot.com',
    iosBundleId: 'com.beyondthebox.mgame.RunnerTests',
  );
}
